Lambda=0.5;             % rate of vegetation growth per unit soil water
E=10;                   % root to shoot ratio
K=0.9;                   % maximal standing biomass per unit area
M=11.4;                 % plant mortality rate 
DB=1.2;                 % seed dispersal rate
P=400.0;                  % precipitation
N=20.0;                 % evaporation rate
R=0.01;                 % Reduction in evaporation due to shading (dimensionless)
GamW=10.0;              % water uptake rate
DW=150;                 % lateral soil water diffusion  
mH=0.06;                 % herbivore mortality rate 
GamH=0.3;               % fraction of consumed biomass used in herbivore production
BetaH=0.82;             % satiaton biomass 
DHH=400;             % maximal random motility
Zeta=0.001;             % reference biomass at which the motility drops to 50%
DHB=700;               % maximal vegetaxis motility
k=0.0001;               % reference biomass at which the motility drops to 50%
K_H=175;                % maximum herbivore capacity per unit area
s=0;                    % speed